### ISSUE TITLE
Blank Webpage after install

### ISSUE THREAD

**Issue by Rustymage** [nextcloud/nextcloudpi#815]
Evening all,

I have an issue.

I installed Nextcloudpi using this method

`curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | sudo bash
`

It all went well. I then figured out that I needed to enable ncp-web. I can now login but then I get a blank webpage. The tab shows 'NextCloudPi Panel' but that's it. See attached screenshot.

This is running on a RPi3B+ with a 15G SD card (reasonably new) and 1TB HDD. The Pi is running Syncthing. It also has rclone and youtube-dl workloads but these are sporadic.

Please assist - I will try to explain more when you ask questions.

Thanks in advance.

Rustymage

PS: I wonder if it has something to do with the following?

`[Mon Feb 25 22:27:02.515184 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:53991] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name`

<img width="790" alt="screenshot 2019-02-25 22 27 56" src="https://user-images.githubusercontent.com/19926955/53373717-2d321500-394e-11e9-846a-074c6d6f0640.png">

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.8.4
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda 
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      2.8G/15G
rootfs usage         2.8G/15G
swapfile             /var/swap
dbdir                /media/USBdrive/ncdatabase
Nextcloud check      ok
Nextcloud version    15.0.4.0
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               47min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "11": "<!DOCTYPE HTML PUBLIC \"-\/\/IETF\/\/DTD HTML 2.0\/\/EN\">\n<html><head>\n<title>302 Found<\/title>\n<\/head><body>\n<h1>Found<\/h1>\n<p>The document has moved <a href=\"https:\/\/icanhazip.com\/\">here<\/a>.<\/p>\n<\/body><\/html>",
            "1": "192.168.1.143",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Mon Feb 25 22:27:02.414471 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:53991] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:02.515184 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:53991] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:02.639606 2019] [proxy_fcgi:error] [pid 4773:tid 1682572336] [client 192.168.1.122:53991] AH01071: Got error 'PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/ncp-web/index.php:1) in /var/www/ncp-web/index.php on line 24\n'
[Mon Feb 25 22:27:04.254241 2019] [authz_host:error] [pid 4774:tid 1682572336] [client 192.168.1.122:53993] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:04.443571 2019] [authz_host:error] [pid 4774:tid 1682572336] [client 192.168.1.122:53993] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:04.443986 2019] [authz_host:error] [pid 4774:tid 1682572336] [client 192.168.1.122:53993] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:04.545781 2019] [authz_host:error] [pid 4774:tid 1682572336] [client 192.168.1.122:53993] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:04.671089 2019] [proxy_fcgi:error] [pid 4774:tid 1682572336] [client 192.168.1.122:53993] AH01071: Got error 'PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/ncp-web/index.php:1) in /var/www/ncp-web/index.php on line 24\n'
[Mon Feb 25 22:27:19.102214 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54052] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:23.490099 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54055] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:23.653357 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54055] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:23.653767 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54055] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:23.754677 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54055] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:23.879667 2019] [proxy_fcgi:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54055] AH01071: Got error 'PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/ncp-web/index.php:1) in /var/www/ncp-web/index.php on line 24\n'
[Mon Feb 25 22:27:30.723552 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54060] AH01753: access check of 'localhost' to /favicon.ico failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:36.940041 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54066] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:37.085494 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54066] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:37.085928 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54066] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:37.187892 2019] [authz_host:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54066] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Mon Feb 25 22:27:37.313331 2019] [proxy_fcgi:error] [pid 4773:tid 1682572336] [client 192.168.1.122:54066] AH01071: Got error 'PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/ncp-web/index.php:1) in /var/www/ncp-web/index.php on line 24\n'

```
</details>

<details>
<summary>Database logs</summary>

```

2019-02-25 22:13:36 1971110720 [Note] /usr/sbin/mysqld: Shutdown complete

2019-02-25 22:14:05 1989115696 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2019-02-25 22:14:05 1989115696 [Note] InnoDB: The InnoDB memory heap is disabled
2019-02-25 22:14:05 1989115696 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-02-25 22:14:05 1989115696 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2019-02-25 22:14:05 1989115696 [Note] InnoDB: Compressed tables use zlib 1.2.8
2019-02-25 22:14:05 1989115696 [Note] InnoDB: Using Linux native AIO
2019-02-25 22:14:05 1989115696 [Note] InnoDB: Using generic crc32 instructions
2019-02-25 22:14:05 1989115696 [Note] InnoDB: Initializing buffer pool, size = 370.0M
2019-02-25 22:14:05 1989115696 [Note] InnoDB: Completed initialization of buffer pool
2019-02-25 22:14:05 1989115696 [Note] InnoDB: Highest supported file format is Barracuda.
2019-02-25 22:14:06 1989115696 [Note] InnoDB: 128 rollback segment(s) are active.
2019-02-25 22:14:06 1989115696 [Note] InnoDB: Waiting for purge to start
2019-02-25 22:14:06 1989115696 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.41-84.1 started; log sequence number 4095989
2019-02-25 22:14:06 1989115696 [Note] Plugin 'FEEDBACK' is disabled.
2019-02-25 22:14:06 1107292992 [Note] InnoDB: Dumping buffer pool(s) not yet started
2019-02-25 22:14:06 1989115696 [Note] Server socket created on IP: '127.0.0.1'.
2019-02-25 22:14:06 1989115696 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.37-MariaDB-0+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Raspbian 9.0

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"dN6yeiwEBulDVHQrUA5n","level":3,"time":"2019-02-25T21:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":660,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/cron.php","line":41,"args":["\/var\/www\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/base.php","Line":277,"CustomMessage":"--"},"userAgent":"--","version":""}

```
</details>

**Comment by nachoparker** [comment]
it should be fixed now. Please try again from scratch

**Comment by Rustymage** [comment]
Thanks - remove and reinstall with the first code insert I posted?

What was the issue? How can I debug myself next time?

:)

**Comment by Rustymage** [comment]
Can you also tell me how to remove Nextcloud please.

**Comment by Rustymage** [comment]
I've uninstalled mysqld and associated components and it still doesn't work. I'm restoring an old image without NCPi installed to try once more.

**Comment by Rustymage** [comment]
<img width="784" alt="screenshot 2019-02-26 20 48 14" src="https://user-images.githubusercontent.com/19926955/53445184-e43e9700-3a07-11e9-9b1c-16fb5abe3c3e.png">

Hmm - is this meant to happen?

**Comment by Rustymage** [comment]
All working now. Thanks.

**Comment by nachoparker** [comment]
Hi, I was away for a few days. I am glad it works

**Comment by nachoparker** [comment]
I am not sure yet, I rolled back the last changes. I will look into it soon
